# Generated manually for the initial project baseline.
import uuid
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="ChecklistProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("config", models.JSONField(default=dict)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-is_active", "-updated_at"]},
        ),
        migrations.CreateModel(
            name="ScanRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("profile_snapshot", models.JSONField(default=dict)),
                ("requested_steps", models.JSONField(default=list)),
                ("mode_requested", models.CharField(default="FULL_SCAN_EXECUTION", max_length=40)),
                ("mode_validated", models.CharField(default="FULL_SCAN_RESEARCH", max_length=40)),
                ("status", models.CharField(default="QUEUED", max_length=32)),
                ("current_step", models.CharField(blank=True, max_length=40)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("counters", models.JSONField(default=dict)),
                ("results", models.JSONField(default=dict)),
                ("validation", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="scan_runs", to="scanner.checklistprofile")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="StepSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step_key", models.CharField(max_length=40)),
                ("sequence", models.PositiveSmallIntegerField()),
                ("auto_enabled", models.BooleanField(default=False)),
                ("interval_minutes", models.PositiveIntegerField(default=240)),
                ("total_scan_policy", models.CharField(default="REFRESH_IF_STALE", max_length=32)),
                ("notify_on_complete", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="step_schedules", to="scanner.checklistprofile")),
            ],
            options={"ordering": ["sequence"], "unique_together": {("profile", "step_key")}},
        ),
        migrations.CreateModel(
            name="ScanStepRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("step_key", models.CharField(max_length=40)),
                ("sequence", models.PositiveSmallIntegerField()),
                ("status", models.CharField(default="WAITING", max_length=32)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("message", models.CharField(blank=True, max_length=300)),
                ("policy", models.CharField(blank=True, max_length=32)),
                ("payload", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("scan_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="scanner.scanrun")),
            ],
            options={"ordering": ["sequence"], "unique_together": {("scan_run", "step_key")}},
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("coingecko_id", models.CharField(blank=True, max_length=160)),
                ("symbol", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=160)),
                ("binance_pair", models.CharField(blank=True, max_length=40)),
                ("stage", models.CharField(default="UNIVERSE", max_length=40)),
                ("rank", models.PositiveIntegerField(default=0)),
                ("market_cap_usd", models.DecimalField(blank=True, decimal_places=4, max_digits=28, null=True)),
                ("fdv_usd", models.DecimalField(blank=True, decimal_places=4, max_digits=28, null=True)),
                ("volume_24h_usd", models.DecimalField(blank=True, decimal_places=4, max_digits=28, null=True)),
                ("price_usd", models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True)),
                ("quality_score_low", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("quality_score_high", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("quality_status", models.CharField(default="NOT_SCORED", max_length=24)),
                ("entry_score", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("entry_status", models.CharField(default="NOT_SCORED", max_length=24)),
                ("opportunity_score", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("opportunity_status", models.CharField(default="NOT_SCORED", max_length=24)),
                ("action", models.CharField(default="WATCH_ONLY", max_length=40)),
                ("risk_codes", models.JSONField(default=list)),
                ("details", models.JSONField(default=dict)),
                ("scan_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="candidates", to="scanner.scanrun")),
            ],
            options={"ordering": ["rank", "-market_cap_usd"]},
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.CharField(default="INFO", max_length=16)),
                ("title", models.CharField(max_length=180)),
                ("message", models.TextField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scan_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="scanner.scanrun")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="candidate", index=models.Index(fields=["scan_run", "stage"], name="scanner_can_scan_ru_7f07c5_idx")),
        migrations.AddIndex(model_name="candidate", index=models.Index(fields=["symbol"], name="scanner_can_symbol_e870dd_idx")),
    ]
