# Generated by Django 5.2.17 on 2026-08-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_marketregimeglobalsnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='candidate',
            new_name='scanner_can_scan_ru_faea4b_idx',
            old_name='scanner_can_scan_ru_7f07c5_idx',
        ),
        migrations.RenameIndex(
            model_name='candidate',
            new_name='scanner_can_symbol_ee69a7_idx',
            old_name='scanner_can_symbol_e870dd_idx',
        ),
        migrations.RenameIndex(
            model_name='marketregimeglobalsnapshot',
            new_name='scanner_mar_provide_4f3233_idx',
            old_name='scanner_mar_provider_3c5d38_idx',
        ),
        migrations.AlterField(
            model_name='scanrun',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('PAUSED', 'PAUSED'), ('COMPLETED', 'COMPLETED'), ('COMPLETED_WITH_WARNINGS', 'COMPLETED_WITH_WARNINGS'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='QUEUED', max_length=32),
        ),
        migrations.AlterField(
            model_name='stepschedule',
            name='total_scan_policy',
            field=models.CharField(choices=[('ALWAYS_REFRESH', 'Luôn lấy dữ liệu mới'), ('REFRESH_IF_STALE', 'Chỉ lấy lại nếu dữ liệu cũ'), ('USE_LATEST_VALID', 'Dùng dữ liệu hợp lệ gần nhất')], default='REFRESH_IF_STALE', max_length=32),
        ),
    ]
