# Generated by Django 5.2.17 on 2026-08-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_notification_step_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlockOfficialSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coingecko_id', models.CharField(db_index=True, max_length=160)),
                ('symbol', models.CharField(max_length=30)),
                ('project_name', models.CharField(max_length=160)),
                ('chain', models.CharField(blank=True, max_length=80)),
                ('contract', models.CharField(blank=True, max_length=180)),
                ('source_url', models.URLField(max_length=500)),
                ('source_title', models.CharField(blank=True, max_length=240)),
                ('verified_at', models.DateTimeField()),
                ('schema_version', models.CharField(default='unlock.v1', max_length=32)),
                ('schedule_payload', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['coingecko_id', 'is_active'], name='scanner_unl_coingec_6d5801_idx'), models.Index(fields=['contract', 'is_active'], name='scanner_unl_contrac_82ab16_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnlockProviderSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_key', models.CharField(max_length=240)),
                ('provider', models.CharField(max_length=64)),
                ('provider_asset_id', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(max_length=24)),
                ('evidence_type', models.CharField(blank=True, max_length=32)),
                ('confidence', models.CharField(blank=True, max_length=16)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('parser_version', models.CharField(default='unlock.v1', max_length=32)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'indexes': [models.Index(fields=['identity_key', 'provider', 'fetched_at'], name='scanner_unl_identit_6a9844_idx'), models.Index(fields=['expires_at'], name='scanner_unl_expires_a64a93_idx')],
            },
        ),
    ]
