# Generated by Django 5.2.17 on 2026-08-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_unlockofficialschedule_unlockprovidersnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockofficialschedule',
            name='confidence',
            field=models.CharField(default='MEDIUM', max_length=16),
        ),
        migrations.AddField(
            model_name='unlockofficialschedule',
            name='coverage_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unlockofficialschedule',
            name='coverage_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unlockofficialschedule',
            name='evidence_type',
            field=models.CharField(default='OFFICIAL_SCHEDULE', max_length=32),
        ),
        migrations.AddField(
            model_name='unlockofficialschedule',
            name='is_complete_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unlockofficialschedule',
            name='parser_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='unlockofficialschedule',
            name='payload_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='unlockofficialschedule',
            name='source_domain',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='unlockofficialschedule',
            name='source_family',
            field=models.CharField(default='PROJECT_OFFICIAL', max_length=48),
        ),
        migrations.AddField(
            model_name='unlockofficialschedule',
            name='source_type',
            field=models.CharField(default='OFFICIAL_DOCS', max_length=48),
        ),
        migrations.AddField(
            model_name='unlockofficialschedule',
            name='upstream_provider',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='unlockofficialschedule',
            name='verification_state',
            field=models.CharField(default='NEEDS_REVIEW', max_length=24),
        ),
    ]
