using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Windows;
using CryptoScanner.Desktop.Helpers;
using CryptoScanner.Desktop.Models;
using CryptoScanner.Desktop.Services;
namespace CryptoScanner.Desktop.ViewModels;
public sealed class MainViewModel:ObservableObject
{
 readonly ScannerService _scanner=new(); readonly ExportService _export=new(); readonly List<ScanResult> _rawResults=[]; CancellationTokenSource? _cts; bool _busy; bool _hasScanned; bool _scanFailed; double _progress; string _status="Sẵn sàng"; string _stage="Idle"; string _btc="UNKNOWN"; int _scanned; int _progressCurrent; int _progressTotal; DateTimeOffset? _updated; CoinDisplayItem? _selectedCoin;
 public ObservableCollection<CoinDisplayItem> DisplayResults {get;}=[];
 public CoinDisplayItem? SelectedCoin{get=>_selectedCoin;set=>Set(ref _selectedCoin,value);}
 public RelayCommand ScanCommand {get;} public RelayCommand CancelCommand {get;} public RelayCommand ExportCommand {get;} public RelayCommand OpenExportFolderCommand {get;} public RelayCommand OpenLogFolderCommand {get;}
 public MainViewModel(){ScanCommand=new(async _=>await ScanAsync(),_=>!_busy);CancelCommand=new(_=>_cts?.Cancel(),_=>_busy);ExportCommand=new(async _=>await ExportAsync(),_=>_rawResults.Count>0&&!_busy);OpenExportFolderCommand=new(_=>OpenExportFolder());OpenLogFolderCommand=new(_=>OpenLogFolder());}
 public double Progress{get=>_progress;set=>Set(ref _progress,value);} public string StatusMessage{get=>_status;set=>Set(ref _status,value);} public string ProgressStage{get=>_stage;set=>Set(ref _stage,value);} public int ProgressCurrent{get=>_progressCurrent;set=>Set(ref _progressCurrent,value);} public int ProgressTotal{get=>_progressTotal;set=>Set(ref _progressTotal,value);} public string ProgressDetail=>ProgressTotal>0?$"{ProgressStage}: {ProgressCurrent}/{ProgressTotal}":ProgressStage;
 public string BtcRegime{get=>_btc;set=>Set(ref _btc,value);} public int ScannedCount{get=>_scanned;set=>Set(ref _scanned,value);} public int PassedCount=>DisplayResults.Count; public int BuyReadyCount=>DisplayResults.Count(x=>x.Source.Status=="BUY_READY"); public string UpdatedAt=>_updated?.ToString("dd/MM/yyyy HH:mm")??"--";
 public bool HasResults=>DisplayResults.Count>0; public bool ShowInitialState=>!_busy&&!_hasScanned&&!HasResults&&!_scanFailed; public bool ShowNoResultsState=>!_busy&&_hasScanned&&!HasResults&&!_scanFailed; public bool ShowErrorState=>_scanFailed;
 async Task ScanAsync(){_busy=true;_hasScanned=true;_scanFailed=false;RefreshCommands();ClearResults();try{AppLogger.Info("Scan command started");_cts=new CancellationTokenSource();var p=new Progress<(double,string)>(x=>UpdateProgress(x.Item1,x.Item2));var data=await _scanner.ScanAsync(p,_cts.Token);_rawResults.AddRange(data.Results);foreach(var x in _rawResults)DisplayResults.Add(new CoinDisplayItem(x));SelectedCoin=DisplayResults.FirstOrDefault();ScannedCount=data.Scanned;BtcRegime=data.BtcRegime;_updated=DateTimeOffset.Now;RaiseSummary();AppLogger.Info($"Scan command completed; scanned={ScannedCount}; results={DisplayResults.Count}; logDir={AppLogger.LogDirectory}");}catch(OperationCanceledException){StatusMessage="Đã hủy.";ProgressStage="Canceled";AppLogger.Warn("Scan command canceled");}catch(Exception ex){_scanFailed=true;StatusMessage="Quét thất bại. Xem log để biết chi tiết.";ProgressStage="Error";AppLogger.Error("Scan command failed",ex);MessageBox.Show(ex.ToString(),"Scanner error");}finally{_busy=false;RaiseStates();RefreshCommands();}}
 async Task ExportAsync(){try{AppLogger.Info("Export command started");var path=await _export.ExportAsync(_rawResults,BtcRegime,ScannedCount);StatusMessage="Đã xuất: "+path;MessageBox.Show(path,"Xuất JSON thành công");}catch(Exception ex){AppLogger.Error("Export command failed",ex);MessageBox.Show(ex.Message,"Export error");}}
 void OpenExportFolder(){try{Directory.CreateDirectory(ExportService.ExportDirectory);Process.Start(new ProcessStartInfo{FileName=ExportService.ExportDirectory,UseShellExecute=true});StatusMessage="Đã mở thư mục export: "+ExportService.ExportDirectory;AppLogger.Info("Opened export folder: "+ExportService.ExportDirectory);}catch(Exception ex){AppLogger.Error("Open export folder failed",ex);MessageBox.Show(ex.Message,"Open export folder error");}}
 void OpenLogFolder(){try{Directory.CreateDirectory(AppLogger.LogDirectory);Process.Start(new ProcessStartInfo{FileName=AppLogger.LogDirectory,UseShellExecute=true});StatusMessage="Đã mở thư mục log: "+AppLogger.LogDirectory;AppLogger.Info("Opened log folder: "+AppLogger.LogDirectory);}catch(Exception ex){AppLogger.Error("Open log folder failed",ex);MessageBox.Show(ex.Message,"Open log folder error");}}
 void ClearResults(){_rawResults.Clear();DisplayResults.Clear();SelectedCoin=null;ScannedCount=0;Progress=0;ProgressCurrent=0;ProgressTotal=0;ProgressStage="Starting";StatusMessage="Đang chuẩn bị quét...";RaiseSummary();}
 void UpdateProgress(double percent,string message){Progress=percent;StatusMessage=message;ParseProgress(message);Raise(nameof(ProgressDetail));}
 void ParseProgress(string message){if(message.Contains("CoinGecko",StringComparison.OrdinalIgnoreCase)){ProgressStage="CoinGecko";ProgressCurrent=0;ProgressTotal=0;}else if(message.Contains("Binance",StringComparison.OrdinalIgnoreCase)){ProgressStage="Binance";ProgressCurrent=0;ProgressTotal=0;}else if(message.Contains("Phân tích",StringComparison.OrdinalIgnoreCase)){ProgressStage="Technical";var start=message.LastIndexOf('(');var slash=message.LastIndexOf('/');var end=message.LastIndexOf(')');if(start>=0&&slash>start&&end>slash&&int.TryParse(message[(start+1)..slash],out var current)&&int.TryParse(message[(slash+1)..end],out var total)){ProgressCurrent=current;ProgressTotal=total;}}else if(message.Contains("Hoàn tất",StringComparison.OrdinalIgnoreCase)){ProgressStage="Completed";ProgressCurrent=ProgressTotal;}}
 void RaiseSummary(){Raise(nameof(PassedCount));Raise(nameof(BuyReadyCount));Raise(nameof(UpdatedAt));RaiseStates();}
 void RaiseStates(){Raise(nameof(HasResults));Raise(nameof(ShowInitialState));Raise(nameof(ShowNoResultsState));Raise(nameof(ShowErrorState));}
 void RefreshCommands(){ScanCommand.RaiseCanExecuteChanged();CancelCommand.RaiseCanExecuteChanged();ExportCommand.RaiseCanExecuteChanged();}
}
