window.ABX_HUB_GAMES = [
  { title: "Xóc Đĩa Live HIT, GO88, NET88, TX88",                      slug: "xoc-dia-live-hit",        tag: "Xóc đĩa",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/XocDiaLiveHit.png" },
  { title: "Xóc Đĩa Phụng Tứ Linh HIT",                                slug: "xoc-dia-tu-linh-hit",     tag: "Xóc đĩa",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/XocDiaTuLinhHit.png" },
  { title: "Tài Xỉu Live HIT, GO88, NET88, TX88",                      slug: "tai-xiu-live-hit",        tag: "Tài xỉu",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/TaiXiuLiveHit.png" },
  { title: "Tài Xỉu Live HIT trang chính",                             slug: "tai-xiu-live-hit0",       tag: "Tài xỉu",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/TaiXiuLiveHit.png" },
  { title: "Tài Xỉu Thường HIT",                                       slug: "tai-xiu-thuong-hit",      tag: "Tài xỉu",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/TaiXiuThuongHit.png" },
  { title: "Tài Xỉu MD5 HIT",                                          slug: "tai-xiu-md5-hit",         tag: "Tài xỉu",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/TaiXiuMD5Hit.png" },
  { title: "Aviator HIT, GO88, NET88, TX88",                           slug: "aviator-hit",             tag: "aviator",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/AviatorHit.png" },
  { title: "Xóc Đĩa Tứ Linh SunWin, ZoWin, NhatVip, GemVip",           slug: "xoc-dia-tu-linh-zowin",   tag: "Xóc đĩa",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/XocDiaTuLinhZoWin.png" },
  { title: "Tài Xỉu Thường SunWin, ZoWin, NhatVip, GemVip",            slug: "tai-xiu-thuong-zowin",    tag: "Tài xỉu",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/TaiXiuThuongZoWin.png" },
  { title: "Tài Xỉu Live SunWin, ZoWin, NhatVip, GemVip",              slug: "tai-xiu-live-sunwin",     tag: "Tài xỉu",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/TaiXiuLiveSunWin.png" },
  { title: "Sicbo X88 Live SunWin, ZoWin, NhatVip, GemVip",            slug: "sic-bo-live-sunwin",      tag: "Tài xỉu Sicbo",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/SicboLiveSunWin.png" },
  { title: "Tài Xỉu B29",                                              slug: "tai-xiu-b29",             tag: "Tài xỉu",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/TaiXiuB29.png" },
  { title: "Xóc Đĩa B29",                                              slug: "xoc-dia-b29",             tag: "Xóc đĩa",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/XocDiaB29.png" },
  { title: "Xóc Đĩa B52",                                              slug: "xoc-dia-b52",             tag: "Xóc đĩa",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/XocDiaB52.png" },
  { title: "Xóc Đĩa Sới Live KH24",                                    slug: "xoc-dia-soi-live-kh24",   tag: "Xóc đĩa",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/XocDiaSoiLiveKH24.png" },
  { title: "Xóc Đĩa Sới Vip 389",                                      slug: "xoc-dia-soi-vip389",      tag: "Xóc đĩa",  gradient: "from-rose-500 to-fuchsia-500", img: "Assets/XocDiaSoiVip389.png" },
  { title: "Baccarat Sảnh PP Casino trực tuyến",                       slug: "baccarat-pp-rr88",        tag: "Baccarat", gradient: "from-rose-500 to-fuchsia-500", img: "Assets/BaccaratPPRR88.png" },
  { title: "Baccarat Sexy Casino Nhóm 1 : Duba Palace",                slug: "baccarat-sexy-casino",    tag: "Baccarat", gradient: "from-rose-500 to-fuchsia-500", img: "Assets/BaccaratSexyCasino.png" },
  { title: "Baccarat Sexy Casino Nhóm 2 : QH88, UU88, RR88, VIP389, SHBet",   slug: "baccarat-sexy-casino2",   tag: "Baccarat", gradient: "from-rose-500 to-fuchsia-500", img: "Assets/BaccaratSexyCasino.png" },
  { title: "Baccarat WM Casino Nhóm 1 : Duba Palace",                  slug: "baccarat-wm-casino",      tag: "Baccarat", gradient: "from-rose-500 to-fuchsia-500", img: "Assets/BaccaratWMCasino.png" },
  { title: "Baccarat WM Casino Nhóm 2 : QH88, UU88, RR88, VIP389,SHBet",     slug: "baccarat-wm-casino2",     tag: "Baccarat", gradient: "from-rose-500 to-fuchsia-500", img: "Assets/BaccaratWMCasino.png" },
  { title: "Baccarat Sảnh Vivo Gaming trực tuyến",                     slug: "baccarat-vivo-gaming",    tag: "Baccarat", gradient: "from-rose-500 to-fuchsia-500", img: "Assets/BaccaratVivoGaming.png" },
  { title: "Baccarat Sảnh Ezugi trực tuyến",                           slug: "baccarat-ezugi-casino",   tag: "Baccarat", gradient: "from-rose-500 to-fuchsia-500", img: "Assets/BaccaratEzugiCasino.png" },
  { title: "Baccarat Sảnh Pragmatic trực tuyến",                       slug: "baccarat-pragmatic",      tag: "Baccarat", gradient: "from-rose-500 to-fuchsia-500", img: "Assets/BaccaratPragmatic.png" },
  { title: "Baccarat ZoWin Live",                                      slug: "baccarat-zowin-casino",   tag: "Baccarat", gradient: "from-rose-500 to-fuchsia-500", img: "Assets/BaccaratZoWin.png" },
];
